#!/bin/bash

ENV="../.env"

while IFS='=' read -r key value; do
    
    #
    # Skip comments and empty lines
    if [[ -z "$key" || "$key" =~ ^# ]]; then
        continue
    fi

    # Remove potential surrounding quotes and whitespace
    key=$(echo "$key" | xargs)
    value=$(echo "$value" | xargs)

    echo "key... $key"
    echo "value... $value"

    export "$key=$value"

done < .env

